// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoF93eBBiAgS20cWGC397WmsLrLXJ9aKQ',
    appId: '1:535259196877:web:cf247dd797006c10e9e884',
    messagingSenderId: '535259196877',
    projectId: 'mobile2final-999b7',
    authDomain: 'mobile2final-999b7.firebaseapp.com',
    storageBucket: 'mobile2final-999b7.firebasestorage.app',
    measurementId: 'G-QCV3VCPF5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntSSW0d2GwSypdDM4ji1_9ERlW2h202k',
    appId: '1:535259196877:android:e20a912987d92cb1e9e884',
    messagingSenderId: '535259196877',
    projectId: 'mobile2final-999b7',
    storageBucket: 'mobile2final-999b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvEbrIvAedTSNp3y9-Sl2dfyJNfKitkw',
    appId: '1:535259196877:ios:d4ea5ba97eb9c6c1e9e884',
    messagingSenderId: '535259196877',
    projectId: 'mobile2final-999b7',
    storageBucket: 'mobile2final-999b7.firebasestorage.app',
    iosBundleId: 'com.example.mobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvEbrIvAedTSNp3y9-Sl2dfyJNfKitkw',
    appId: '1:535259196877:ios:d4ea5ba97eb9c6c1e9e884',
    messagingSenderId: '535259196877',
    projectId: 'mobile2final-999b7',
    storageBucket: 'mobile2final-999b7.firebasestorage.app',
    iosBundleId: 'com.example.mobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoF93eBBiAgS20cWGC397WmsLrLXJ9aKQ',
    appId: '1:535259196877:web:707d63a1f05c89b9e9e884',
    messagingSenderId: '535259196877',
    projectId: 'mobile2final-999b7',
    authDomain: 'mobile2final-999b7.firebaseapp.com',
    storageBucket: 'mobile2final-999b7.firebasestorage.app',
    measurementId: 'G-WKR38ZS5VV',
  );

}